---

- hosts: local
  connection: local
  tasks:
    - name: Get Client IP
      uri:
        url: http://checkip.amazonaws.com/
        return_content: yes
      register: clt_ip

    - name: Create a httpd group
      ec2_group:
        name: httpd-server
        description: A security group for access
        region: ap-southeast-2
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
        rules_egress:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
      register: httpd_group
      tags:
        create_httpd_group

    - name: Create ELB
      ec2_elb_lb:
        name: httpd-balancer
        state: present
        region: ap-southeast-2
        zones:
          - ap-southeast-2a
          - ap-southeast-2b
        listeners:
          - protocol: http
            load_balancer_port: 80
            instance_port: 80
      register: elb
      tags: 
        create_elb
    
    - action:
        module: ec2_elb_facts
        region: ap-southeast-2
      register: elb_facts

    - local_action:
        module: copy
        content: "{{ item.dns_name }}"
        dest: url_loadbalance_httpd.txt
      with_items: "{{ elb_facts.elbs }}"

    - name: Generate a EC2 Key
      ec2_key:
        name: ec2key
        region: ap-southeast-2
      register: ec2_key_result
      tags:
        generate_ec2_key

    - name: Save key
      copy: content="{{ ec2_key_result.key.private_key }}" dest="./ec2key" mode=0600
      when: ec2_key_result.changed
      tags:
        save_key

    - name: Create EC2
      ec2:
        key_name: ec2key
        instance_type: t2.micro
        image: ami-04481c741a0311bbb
        region: ap-southeast-2
        group_id:
          - "{{ httpd_group.group_id }}"
          - "{{ elb.elb.security_group_ids | first }}"
        wait: yes
        instance_tags:
          application: WebApp-AWS
        exact_count: 1
        count_tag:
          application: WebApp-AWS
      register: ec2_server
      tags:
        create_ec2
      
    - name: Get EC2 information
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: ec2_server_ip
      with_items: "{{ ec2_server.tagged_instances }}"
      
    - name: Test server connection
      wait_for:
        host: "{{ item.public_ip }}"
        port: 22
        timeout: 300
      with_items: "{{ ec2_server.tagged_instances }}"
      tags:
        test_connection

    - name: Include EC2 keys to known hosts
      known_hosts:
        name: "{{ item.public_ip }}"
        key: "{{ lookup('pipe', 'ssh-keyscan -t rsa ' + item.public_ip) }}"
      with_items: "{{ ec2_server.tagged_instances }}"

    - name: Add pem to local ssh
      local_action: 
        module: shell
           ssh-add ec2key
    
    - name: Create a new disk
      ec2_vol:
        region: ap-southeast-2
        instance: "{{ item.id }}"
        volume_size: 5
        device_name: /dev/xvdg
      with_items: "{{ ec2_server.tagged_instances }}"
      tags:
        create_disk

- hosts: ec2_server_ip
  remote_user: ec2-user
  become: True
  tasks:
    - name: Modify Sysctl to disable IPV6
      shell:
        echo -e "net.ipv6.conf.all.disable_ipv6 = 1\nnet.ipv6.conf.default.disable_ipv6 = 1" | sudo tee -a /etc/sysctl.conf

    - name: Reload values for Sysctl
      shell:
        sudo sysctl -p

    - name: Include Address Family to sshd
      shell:
        echo "AddressFamily inet" | sudo tee -a /etc/ssh/sshd_config

    - name: Restart SSHD
      systemd:
        name: sshd
        state: restarted

    - name: Install lvm packages
      yum:
        name: 'lvm*'
        state: present
    
    - name: Create a VG
      lvg:
        vg: vg
        pvs: /dev/xvdg
        state: present

    - name: Create a LV on top of the new VG
      lvol:
        vg: vg
        lv: lv01
        size: 100%FREE
        
    - name: Format the volume with XFS
      filesystem:
        fstype: xfs
        dev: /dev/mapper/vg-lv01
 
    - name: Mount a new fileshare
      mount:
        path: /var/www/html/
        src: /dev/mapper/vg-lv01
        fstype: xfs
        state: mounted

    - name: Install httpd
      yum:
        name: httpd
        state: present

    - name: Install git
      yum: 
        name: git-all
        state: present


    - name: Clonar repositorio GIT
      git:
        repo: 'https://github.com/Renatovnctavares/WebServer-AWS-byAnsible.git'
        dest: /var/www/html/

    - name: Create default index page
      copy:
        dest: /var/www/html/index.html
        content: "SERVER WEB HAS BEEN CREATED by ansible!! -Server:{{ ansible_hostname }} - Renato Tavares 04/2019 <br> check out the script on: /WebServer-AWS-byAnsible/project.yml"

    - name: Restart httpd
      systemd:
        name: httpd
        state: restarted


    - name: Disable SELinux
      shell:
        sudo setenforce 0 && sudo sed -ri 's/SELINUX=enforcing/SELINUX=disabled/' /etc/selinux/config &

    - name: Stop auditd
      shell:
        sudo service auditd stop 

    - name: Disable auditd
      shell:
        sudo systemctl disable auditd

- hosts: local
  connection: local
  tasks:
    - name: Test server connection again
      wait_for:
        delay: 30
        host: "{{ item.public_ip }}"
        port: 22
        timeout: 300
      with_items: "{{ ec2_server.tagged_instances }}"
      tags:
        test_connection2

- hosts: ec2_server_ip
  remote_user: ec2-user
  become: True
  tasks:
    - name: Restart httpd service
      systemd:
        name: httpd
        state: restarted

- hosts: local
  connection: local
  tasks:
    - name: Adding EC2 to ELB
      ec2_elb: 
        state: present
        ec2_elbs: httpd-balancer
        region: ap-southeast-2
        instance_id: "{{ item.id }}"
      with_items: "{{ ec2_server.tagged_instances }}"

